name: MkDocs Build
on:
  push:
    branches:
      - jtb
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build with MkDocs
      uses: romw314/mkdocs-action@v2
